import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import ProjectsHeader from '@/components/ProjectsHeader'
import SiteFooter from '@/components/SiteFooter'
import { createClient } from '@/lib/supabase/server'
import { getAdminUserIds } from '@/lib/admin'
import { AVAILABILITY_LABEL, formatGBP, type Availability } from '@/lib/projects'
import {
  editProjectVisionAction,
  editProjectModelAction,
  postProjectUpdateAction,
  deleteProjectUpdateAction,
} from '../../actions'

type TierRow = {
  id: string
  name: string
  upfront_amount: number
  monthly_amount: number
  monthly_duration_months: number
  total_amount: number
  target_slots: number
  phase_choice: boolean
  display_order: number
}

type RegistrationRow = {
  id: string
  user_id: string
  tier_id: string
  skills_text: string
  location_text: string
  motivation_text: string
  availability: Availability
  created_at: string
  users: { username: string } | null
}

function formatRegistrationDate(iso: string): string {
  return new Date(iso).toLocaleString('en-GB', {
    dateStyle: 'medium',
    timeStyle: 'short',
  })
}

export default async function ManageProjectPage(
  props: PageProps<'/projects/[projectId]/manage'>
) {
  const { projectId } = await props.params

  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) redirect(`/signin?next=/projects/${projectId}/manage`)

  const adminIds = await getAdminUserIds()

  const { data: project } = await supabase
    .from('projects')
    .select(
      'id, title, vision_content, model_content, pdf_url, creator_id, status, funding_target, per_person_target, project_tiers(id, name, upfront_amount, monthly_amount, monthly_duration_months, total_amount, target_slots, phase_choice, display_order)'
    )
    .eq('id', projectId)
    .maybeSingle<{
      id: string
      title: string
      vision_content: string
      model_content: string
      pdf_url: string | null
      creator_id: string
      status: string
      funding_target: number
      per_person_target: number
      project_tiers: TierRow[]
    }>()

  if (!project) notFound()

  const isCreator = project.creator_id === user.id
  const isAdmin = adminIds.has(user.id)
  if (!isCreator && !isAdmin) {
    redirect(`/projects/${projectId}`)
  }

  const tiers = (project.project_tiers ?? []).sort(
    (a, b) => a.display_order - b.display_order
  )
  const tierById = new Map(tiers.map((t) => [t.id, t]))

  // Registrations — full rows, only the creator can read these via RLS.
  // For an admin who isn't the creator we'd need a service-role read; for
  // now the admin and the creator are the same person on the first project.
  const { data: regs } = await supabase
    .from('project_registrations')
    .select(
      'id, user_id, tier_id, skills_text, location_text, motivation_text, availability, created_at, users:user_id(username)'
    )
    .eq('project_id', projectId)
    .order('created_at', { ascending: true })
    .returns<RegistrationRow[]>()

  const registrations = regs ?? []

  // Stats.
  const totalInterested = registrations.length
  const tierBreakdown = new Map<string, number>()
  const availabilityBreakdown = new Map<string, number>()
  const locationBreakdown = new Map<string, number>()
  let representedFunding = 0

  for (const r of registrations) {
    tierBreakdown.set(r.tier_id, (tierBreakdown.get(r.tier_id) ?? 0) + 1)
    availabilityBreakdown.set(
      r.availability,
      (availabilityBreakdown.get(r.availability) ?? 0) + 1
    )
    const loc = r.location_text.trim() || '(unspecified)'
    locationBreakdown.set(loc, (locationBreakdown.get(loc) ?? 0) + 1)
    const tier = tierById.get(r.tier_id)
    if (tier) representedFunding += Number(tier.total_amount) || 0
  }

  const target = Number(project.funding_target) || 0
  const perPerson = Number(project.per_person_target) || 0
  const distanceFromTarget = Math.max(0, target - representedFunding)
  // Surplus generated by registrations whose tier total exceeds the
  // per-person target (used to "unlock" lower-tier slots).
  let surplus = 0
  for (const r of registrations) {
    const tier = tierById.get(r.tier_id)
    if (!tier) continue
    const tierTotal = Number(tier.total_amount) || 0
    if (tierTotal > perPerson) {
      surplus += tierTotal - perPerson
    }
  }
  const lowestFinancialTier = tiers
    .filter((t) => t.total_amount > 0)
    .reduce<TierRow | null>(
      (acc, t) => (!acc || t.total_amount < acc.total_amount ? t : acc),
      null
    )
  const subsidyPerLowSlot =
    lowestFinancialTier && perPerson > Number(lowestFinancialTier.total_amount)
      ? perPerson - Number(lowestFinancialTier.total_amount)
      : 0
  const unlockedLowSlots =
    subsidyPerLowSlot > 0 ? Math.floor(surplus / subsidyPerLowSlot) : 0

  // Updates (for the deletion list).
  const { data: updatesData } = await supabase
    .from('project_updates')
    .select('id, title, created_at')
    .eq('project_id', projectId)
    .order('created_at', { ascending: false })
    .returns<{ id: string; title: string; created_at: string }[]>()
  const updates = updatesData ?? []

  return (
    <>
      <ProjectsHeader />
      <main className="flex-1 px-4 sm:px-6 py-8 sm:py-12">
        <div className="mx-auto max-w-2xl space-y-14">
          <div>
            <p className="text-sm text-stone-500">
              <Link
                href={`/projects/${projectId}`}
                className="underline hover:text-stone-900"
              >
                ← {project.title}
              </Link>
            </p>
            <h1 className="mt-1 text-2xl font-semibold">Manage project</h1>
          </div>

          {/* Tier health indicator */}
          <section>
            <h2 className="text-xl font-semibold">Tier health</h2>
            <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm">
              <div className="rounded border border-stone-200 bg-stone-50 p-4">
                <p className="text-xs uppercase tracking-wide text-stone-500">
                  Funding represented
                </p>
                <p className="mt-1 text-lg font-semibold text-stone-800">
                  {formatGBP(representedFunding)}
                </p>
                <p className="text-xs text-stone-500">
                  Target: {formatGBP(target)}
                </p>
              </div>
              <div className="rounded border border-stone-200 bg-stone-50 p-4">
                <p className="text-xs uppercase tracking-wide text-stone-500">
                  Distance from target
                </p>
                <p className="mt-1 text-lg font-semibold text-stone-800">
                  {formatGBP(distanceFromTarget)}
                </p>
              </div>
              <div className="rounded border border-stone-200 bg-stone-50 p-4">
                <p className="text-xs uppercase tracking-wide text-stone-500">
                  Surplus from upper tiers
                </p>
                <p className="mt-1 text-lg font-semibold text-stone-800">
                  {formatGBP(surplus)}
                </p>
                <p className="text-xs text-stone-500">
                  Above the {formatGBP(perPerson)} per-person target
                </p>
              </div>
              <div className="rounded border border-stone-200 bg-stone-50 p-4">
                <p className="text-xs uppercase tracking-wide text-stone-500">
                  Lower-tier slots unlocked
                </p>
                <p className="mt-1 text-lg font-semibold text-stone-800">
                  {unlockedLowSlots}
                </p>
                <p className="text-xs text-stone-500">
                  At the lowest financial tier{' '}
                  {lowestFinancialTier ? `(${lowestFinancialTier.name})` : ''}
                </p>
              </div>
            </div>
          </section>

          {/* Summary stats */}
          <section>
            <div className="flex items-center justify-between gap-4">
              <h2 className="text-xl font-semibold">
                Registrations{' '}
                <span className="text-base font-normal text-stone-500">
                  ({totalInterested})
                </span>
              </h2>
              <a
                href={`/projects/${projectId}/manage/export`}
                className="text-sm text-stone-600 underline hover:text-stone-900"
              >
                Export CSV
              </a>
            </div>

            <div className="mt-5 grid grid-cols-1 sm:grid-cols-2 gap-6">
              <div>
                <h3 className="text-sm font-medium text-stone-700">By tier</h3>
                <ul className="mt-2 divide-y divide-stone-200 border-y border-stone-200 text-sm">
                  {tiers.map((t) => (
                    <li key={t.id} className="py-2 flex justify-between">
                      <span className="text-stone-700">{t.name}</span>
                      <span className="text-stone-500">
                        {tierBreakdown.get(t.id) ?? 0} / {t.target_slots}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h3 className="text-sm font-medium text-stone-700">
                  By availability
                </h3>
                <ul className="mt-2 divide-y divide-stone-200 border-y border-stone-200 text-sm">
                  {Array.from(availabilityBreakdown.entries()).map(([k, v]) => (
                    <li key={k} className="py-2 flex justify-between">
                      <span className="text-stone-700">
                        {AVAILABILITY_LABEL[k as Availability] ?? k}
                      </span>
                      <span className="text-stone-500">{v}</span>
                    </li>
                  ))}
                  {availabilityBreakdown.size === 0 && (
                    <li className="py-2 text-stone-500">—</li>
                  )}
                </ul>
              </div>
            </div>

            <div className="mt-6">
              <h3 className="text-sm font-medium text-stone-700">By location</h3>
              <ul className="mt-2 divide-y divide-stone-200 border-y border-stone-200 text-sm">
                {Array.from(locationBreakdown.entries())
                  .sort((a, b) => b[1] - a[1])
                  .slice(0, 20)
                  .map(([k, v]) => (
                    <li key={k} className="py-2 flex justify-between">
                      <span className="text-stone-700">{k}</span>
                      <span className="text-stone-500">{v}</span>
                    </li>
                  ))}
                {locationBreakdown.size === 0 && (
                  <li className="py-2 text-stone-500">—</li>
                )}
              </ul>
            </div>
          </section>

          {/* Full registration list */}
          <section>
            <h2 className="text-xl font-semibold">Individual registrations</h2>
            {registrations.length === 0 ? (
              <p className="mt-3 text-sm text-stone-500">
                No registrations yet.
              </p>
            ) : (
              <ul className="mt-4 divide-y divide-stone-200 border-y border-stone-200">
                {registrations.map((r) => {
                  const tier = tierById.get(r.tier_id)
                  return (
                    <li key={r.id} className="py-4 text-sm">
                      <div className="flex items-baseline justify-between gap-3">
                        <p className="font-medium text-stone-800">
                          {r.users?.username ?? 'unknown'}
                        </p>
                        <p className="text-xs text-stone-400">
                          {formatRegistrationDate(r.created_at)}
                        </p>
                      </div>
                      <p className="mt-1 text-stone-600">
                        Tier:{' '}
                        <span className="text-stone-800">
                          {tier?.name ?? 'unknown'}
                        </span>{' '}
                        · Availability:{' '}
                        <span className="text-stone-800">
                          {AVAILABILITY_LABEL[r.availability] ?? r.availability}
                        </span>
                        {r.location_text && (
                          <>
                            {' · '}
                            <span className="text-stone-800">
                              {r.location_text}
                            </span>
                          </>
                        )}
                      </p>
                      {r.skills_text && (
                        <p className="mt-2">
                          <span className="text-xs text-stone-500">Skills</span>
                          <br />
                          <span className="text-stone-700">{r.skills_text}</span>
                        </p>
                      )}
                      {r.motivation_text && (
                        <p className="mt-2">
                          <span className="text-xs text-stone-500">Motivation</span>
                          <br />
                          <span className="text-stone-700">{r.motivation_text}</span>
                        </p>
                      )}
                    </li>
                  )
                })}
              </ul>
            )}
          </section>

          {/* Post a progress update */}
          <section>
            <h2 className="text-xl font-semibold">Post a progress update</h2>
            <p className="mt-1 text-sm text-stone-500">
              Posted in the project&rsquo;s Progress Updates section. Markdown
              is supported.
            </p>
            <form action={postProjectUpdateAction} className="mt-4 flex flex-col gap-3">
              <input type="hidden" name="project_id" value={projectId} />
              <label className="flex flex-col gap-1 text-sm">
                <span className="text-stone-700 font-medium">Title</span>
                <input
                  name="title"
                  type="text"
                  required
                  maxLength={200}
                  className="rounded border border-stone-300 px-3 py-2 bg-white focus:outline-none focus:ring-2 focus:ring-stone-400"
                />
              </label>
              <label className="flex flex-col gap-1 text-sm">
                <span className="text-stone-700 font-medium">Content (markdown)</span>
                <textarea
                  name="content"
                  required
                  maxLength={50000}
                  rows={8}
                  className="rounded border border-stone-300 px-3 py-2 font-mono text-xs bg-white focus:outline-none focus:ring-2 focus:ring-stone-400"
                />
              </label>
              <div>
                <button
                  type="submit"
                  className="rounded bg-stone-900 text-stone-50 px-4 py-2 text-sm hover:bg-stone-700"
                >
                  Post update
                </button>
              </div>
            </form>

            {updates.length > 0 && (
              <div className="mt-6">
                <h3 className="text-sm font-medium text-stone-700">
                  Existing updates
                </h3>
                <ul className="mt-2 divide-y divide-stone-200 border-y border-stone-200 text-sm">
                  {updates.map((u) => (
                    <li
                      key={u.id}
                      className="py-2 flex items-center justify-between gap-3"
                    >
                      <div className="min-w-0">
                        <p className="truncate text-stone-700">{u.title}</p>
                        <p className="text-xs text-stone-400">
                          {formatRegistrationDate(u.created_at)}
                        </p>
                      </div>
                      <form action={deleteProjectUpdateAction}>
                        <input
                          type="hidden"
                          name="project_id"
                          value={projectId}
                        />
                        <input type="hidden" name="update_id" value={u.id} />
                        <button
                          type="submit"
                          className="text-xs text-stone-400 underline hover:text-red-700"
                          onClick={(e) => {
                            if (!confirm('Delete this update and all its replies?'))
                              e.preventDefault()
                          }}
                        >
                          Delete
                        </button>
                      </form>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </section>

          {/* Edit the vision */}
          <section>
            <h2 className="text-xl font-semibold">Edit the vision</h2>
            <form action={editProjectVisionAction} className="mt-4 flex flex-col gap-3">
              <input type="hidden" name="project_id" value={projectId} />
              <label className="flex flex-col gap-1 text-sm">
                <span className="text-stone-700 font-medium">
                  Vision content (markdown)
                </span>
                <textarea
                  name="vision_content"
                  required
                  maxLength={200000}
                  rows={14}
                  defaultValue={project.vision_content}
                  className="rounded border border-stone-300 px-3 py-2 font-mono text-xs bg-white focus:outline-none focus:ring-2 focus:ring-stone-400"
                />
              </label>
              <label className="flex flex-col gap-1 text-sm">
                <span className="text-stone-700 font-medium">
                  PDF download URL
                </span>
                <input
                  name="pdf_url"
                  type="url"
                  maxLength={1000}
                  defaultValue={project.pdf_url ?? ''}
                  className="rounded border border-stone-300 px-3 py-2 bg-white focus:outline-none focus:ring-2 focus:ring-stone-400"
                />
              </label>
              <div>
                <button
                  type="submit"
                  className="rounded bg-stone-900 text-stone-50 px-4 py-2 text-sm hover:bg-stone-700"
                >
                  Save vision
                </button>
              </div>
            </form>
          </section>

          {/* Edit the model */}
          <section>
            <h2 className="text-xl font-semibold">Edit the model text</h2>
            <form action={editProjectModelAction} className="mt-4 flex flex-col gap-3">
              <input type="hidden" name="project_id" value={projectId} />
              <textarea
                name="model_content"
                required
                maxLength={200000}
                rows={14}
                defaultValue={project.model_content}
                className="rounded border border-stone-300 px-3 py-2 font-mono text-xs bg-white focus:outline-none focus:ring-2 focus:ring-stone-400"
              />
              <div>
                <button
                  type="submit"
                  className="rounded bg-stone-900 text-stone-50 px-4 py-2 text-sm hover:bg-stone-700"
                >
                  Save model text
                </button>
              </div>
            </form>
          </section>
        </div>
      </main>
      <SiteFooter />
    </>
  )
}
